// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkrtoshfjdofymdozjnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcnRvc2hmamRvZnltZG96am5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjAzNTAsImV4cCI6MjA2NzAzNjM1MH0.R8yZ7sbZSpPwlrNbpyDaRm7izM1-tjKjW1j_HB5PGLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});